name: Deployment

on:
    push:
        branches: [master, main]

jobs:
    push_to_gitlab:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Push to Gitlab
              env:
                TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
              run: |
                git fetch --unshallow "https://github.com/t1001001/prog2005-assig02.git"
                git config user.name "t1001001"
                git config user.email "tobias1001001@proton.me"
                git remote set-url origin "https://oauth2:$TOKEN@git.gvk.idi.ntnu.no/course/prog2005/prog2005-2025-workspace/tobi/prog2005-assignment-02.git"
                git push -u origin --all
                git push -u origin --tags
      
      